Plateau degeu
CIASIE-2018/Trivial-Navigo pull request #9
Opened 2018-10-09 09:08 UTC by QuentinRimet

2018-10-09 09:11 UTC, ElGitariste commented
Ok ça à l'air bon !

2018-10-15 12:31 UTC, floo51 requested changes

2018-10-15 12:31 UTC, floo51 commented on index.php
> +	$acc = new jeuControlleur();
Naming should be in english.

2018-10-15 12:31 UTC, floo51 commented on index.php
> +	$acc->affichageJeu();
A method should start with a verb, not a noun. It's an action, not an object.

2018-10-15 12:31 UTC, floo51 commented on src/Jeu.php
> +    public function getPlateau(){
Is there a point having a getter instead of making your `$plateau` property public?

2018-10-15 12:31 UTC, floo51 commented on src/Plateau.php
> +    for($i=1;$i<=$this->taille_tab;$i++){
This is hardly readable, some clues:
- Can you write this code in another way? Maybe just initialize the table without any for loops (the table doesn't change size right?)
- Can you try to externalize some of the code to named functions?
- Can you take more care with variable naming? `$i` and `$j` usually can be replaced with things like `$column` and `$row`

2018-10-15 12:31 UTC, floo51 commented on src/Plateau.php
> +                    case 0:$this->tableau[$i][$j]=["theme"=>"geo","player"=>array()];
`"geo", "diver", ...` are called magic strings and are hell for maintainability. Use constants instead?

2018-10-15 12:31 UTC, floo51 commented on src/Plateau.php
> +    function getTableau(){
Is there a point having a getter instead of a public property?

2018-10-15 12:31 UTC, floo51 commented on src/Plateau.php
> +        return $this->taille_tab;
Does the game board size actually change? If not, why use a variable?

2018-10-15 12:31 UTC, floo51 commented on src/vues/JeuVue.php
> +    public function renderPlateau($plateau){
This is not OK. You can't have a templating engine AND generate html with string concatenation.

2018-10-15 12:31 UTC, floo51 commented on src/vues/JeuVue.php
> +        $ach = GlobaleVue::header();
Be careful with variable naming, I have no idea what `$ach` and `$acf` refer to.

2018-10-16 06:22 UTC, floo51 requested changes

2018-10-16 06:22 UTC, floo51 commented on container.php
> +	$view = $c->get("view"); // retrieve the 'view' from the container
Not sure the comment is needed there, the code explains itself.

2018-10-16 06:22 UTC, floo51 commented on container.php
> +    // Instantiate and add Slim specific extension
This one seems much more needed because I'm not able to understand the 2 lines below 👍

2018-10-16 06:22 UTC, floo51 commented on src/Board.php
> +    $hist="hist";
That's variables, not constants: https://stackoverflow.com/questions/2447791/define-vs-const

2018-10-16 06:22 UTC, floo51 commented on src/Board.php
> +    $this->grid[1][1]=["theme"=>$hist,"player"=>array()];
This is, to me, much more readable than all the loops and switches 👍

2018-10-16 06:22 UTC, floo51 commented on src/vues/GameView.html.twig
> +<table>
Not mandatory for this review, you might want to use more responsive html tags. `div` with css grid by instance: https://css-tricks.com/snippets/css/complete-guide-grid/

2018-10-16 06:22 UTC, floo51 commented on src/vues/GlobalHeaderView.html.twig
> +    </head>
Seems like there are missing closing tags?

2018-10-17 06:32 UTC, floo51 approved these changes

2018-10-17 06:32 UTC, merged